### ISSUE TITLE
add send broadcast support

### ISSUE THREAD

**Issue by qingxp9** [sdaubert/packetgen#50]
when I set the dst to "255.255.255.255",
have the error:
```
irb(main):012:0> PacketGen.gen('IP', src: '192.168.0.6', dst: '255.255.255.255', ttl: 1).to_w

Errno::EACCES: Permission denied - send(2)
	from /var/lib/gems/2.3.0/gems/packetgen-1.4.3/lib/packetgen/header/ip.rb:203:in `send'
	from /var/lib/gems/2.3.0/gems/packetgen-1.4.3/lib/packetgen/header/ip.rb:203:in `to_w'
	from /var/lib/gems/2.3.0/gems/packetgen-1.4.3/lib/packetgen/packet.rb:210:in `to_w'
	from (irb):12
	from /usr/bin/irb:11:in `<main>'
```

**Comment by sdaubert** [comment]
You have to set broadcast on link layer too. Use this in `pgconsole`:
```
$ bundle exec bin/pgconsole
pg(main)> PacketGen.gen('Eth', src: config.hwaddr, dst: 'ff:ff:ff:ff:ff:ff').add('IP', src: '192.168.0.6', dst: '255.255.255.255', ttl: 1).to_w
=> 34
pg(main)>
```

`pgconsole` offers you a config object containing some useful information such as: ethernet address, IP address and IPv6 address of your first ethernet interface.

**Comment by qingxp9** [comment]
Thanks, I get it.
It works.

**Comment by sdaubert** [comment]
OK. I close this issue. Reopen it if you have others troubles related to this issue.
